services:

  wordpress:
    user: "0:0"
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "${ wp_port }:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${ db_user }
      WORDPRESS_DB_PASSWORD: ${ db_password }
      WORDPRESS_DB_NAME: ${ db_name } 
    volumes:
      - ./site:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${ db_name }
      MYSQL_USER: ${ db_user }
      MYSQL_PASSWORD: ${ db_password }
      MYSQL_ROOT_PASSWORD: ${ db_root_password }
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  

      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin4
    restart: always
    depends_on:
      - db
    ports:
      - "${ phpmyadmin_port }:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${ db_root_password }"

volumes:
  db_data:
  wp_data:
